export interface Plant {
  id: string
  commonName: string
  scientificName: string
  type: string
  growthSpeed: string
  nativeStatus: string
  lifespan: string
  biodiversityValue: string
  imageUrl: string
  windResistance: string
  sunExposure: string
  height: number
  droughtResistant: boolean
  description: string
  ecologicalBenefits: string[]
  faunaDependency?: string[]
  bloomingSeason: string
  maintenanceLevel?: string
  dormancyPeriod?: string
  temperatureTolerance?: {
    min: number
    max: number
  }
}

export async function fetchPlants(): Promise<Plant[]> {
  // In a real implementation, this would fetch data from a Google Sheets API
  // For now, we'll return mock data
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "english-ivy",
          commonName: "English Ivy",
          scientificName: "Hedera helix",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/English%20ivy%20%28Hedera%20helix%29-yXVR6O2IjC9yZBd8BFLRLjbI3XOkbf.jpeg",
          windResistance: "high",
          sunExposure: "partial",
          height: 20,
          droughtResistant: true,
          description: "Evergreen climbing vine that attaches to surfaces with aerial rootlets.",
          ecologicalBenefits: ["Provides shelter for wildlife", "Evergreen cover in winter"],
          bloomingSeason: "autumn",
        },
        {
          id: "golden-pothos",
          commonName: "Golden Pothos",
          scientificName: "Epipremnum aureum",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Golden%20pothos%20%28Epipremnum%20aureum%29.jpg-0H8Fal6DVkfoOEKrnU7pJ3JTKfm6ck.jpeg",
          windResistance: "low",
          sunExposure: "shade",
          height: 10,
          droughtResistant: true,
          description: "Trailing vine with heart-shaped leaves variegated with yellow or white.",
          ecologicalBenefits: ["Air purification"],
          bloomingSeason: "rarely blooms",
        },
        {
          id: "ground-ivy",
          commonName: "Ground Ivy",
          scientificName: "Glechoma hederacea",
          type: "groundcover",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ground%20ivy%20%28Glechoma%20hederacea%29.jpg-qzqZP2TDwqXw7CzVvDHCcTEysRsGL6.jpeg",
          windResistance: "high",
          sunExposure: "partial",
          height: 5,
          droughtResistant: true,
          description: "Low-growing, creeping herb with scalloped leaves and small purple flowers.",
          ecologicalBenefits: ["Ground cover", "Early nectar source"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "spring",
        },
        {
          id: "common-yarrow",
          commonName: "Common Yarrow",
          scientificName: "Achillea millefolium",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20yarrow%20%28Achillea%20millefolium%29.jpg-oZR4nVwdmp14ghb8qiIci2JRmH8FDi.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 60,
          droughtResistant: true,
          description: "Herbaceous flowering plant with feathery foliage and flat-topped flower clusters.",
          ecologicalBenefits: ["Attracts pollinators", "Medicinal properties"],
          faunaDependency: ["Butterflies", "Bees"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "chinese-money-plant",
          commonName: "Chinese Money Plant",
          scientificName: "Pilea peperomioides",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chinese%20money%20plant%20%28Pilea%20peperomioides%29.jpg-EbhEQkRhsvVm13NsKkHMvleolqSKVz.jpeg",
          windResistance: "low",
          sunExposure: "partial",
          height: 30,
          droughtResistant: false,
          description: "Round, coin-shaped leaves on long petioles giving a distinctive appearance.",
          bloomingSeason: "spring",
        },
        {
          id: "spider-plant",
          commonName: "Spider Plant",
          scientificName: "Chlorophytum comosum",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Spider%20plant%20%28Chlorophytum%20comosum%29.jpg-kfLWHi4krTaCLbRkygw2B6AOo29Hvn.jpeg",
          windResistance: "low",
          sunExposure: "partial",
          height: 40,
          droughtResistant: true,
          description: "Produces arching stems with plantlets at the ends, resembling spiders.",
          ecologicalBenefits: ["Air purification"],
          bloomingSeason: "summer",
        },
        {
          id: "bigroot-geranium",
          commonName: "Bigroot Geranium 'White'",
          scientificName: "Geranium macrorrhizum 'White'",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/bigroot-geranium.jpg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 30,
          droughtResistant: true,
          description: "Aromatic groundcover with white flowers and lobed leaves that turn red in autumn.",
          ecologicalBenefits: ["Erosion control", "Drought tolerance"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "spring",
        },
        {
          id: "serbian-bellflower",
          commonName: "Serbian Bellflower 'Stella'",
          scientificName: "Campanula poscharskyana 'Stella'",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Serbian%20bellflower%20%22Stella%22.jpg-0PapBxn9QI704q3WA38iY6OnRYD64j.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 15,
          droughtResistant: true,
          description: "Low-growing perennial with star-shaped blue flowers and trailing habit.",
          ecologicalBenefits: ["Attracts pollinators", "Rock garden plant"],
          faunaDependency: ["Bees"],
          bloomingSeason: "summer",
        },
        {
          id: "goldmoss-stonecrop",
          commonName: "Goldmoss Stonecrop",
          scientificName: "Sedum acre",
          type: "succulent",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Goldmoss%20stonecrop%20%28Sedum%20acre%29-fkGF5R7gYulgV04xU2ggRATpmj90en.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 10,
          droughtResistant: true,
          description: "Low-growing succulent with tiny, fleshy leaves and bright yellow star-shaped flowers.",
          ecologicalBenefits: ["Erosion control", "Drought tolerance"],
          faunaDependency: ["Bees"],
          bloomingSeason: "summer",
        },
        {
          id: "buffelgrasses",
          commonName: "Buffelgrasses",
          scientificName: "Cenchrus",
          type: "grass",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl: "/images/buffelgrasses.jpg",
          windResistance: "high",
          sunExposure: "full",
          height: 100,
          droughtResistant: true,
          description: "Drought-resistant grass with fluffy, cylindrical flower spikes.",
          ecologicalBenefits: ["Erosion control", "Drought tolerance"],
          bloomingSeason: "summer",
        },
        {
          id: "bougainvillea",
          commonName: "Bougainvillea",
          scientificName: "Bougainvillea",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/bougainvillea.jpg",
          windResistance: "medium",
          sunExposure: "full",
          height: 300,
          droughtResistant: true,
          description: "Thorny ornamental vine with vibrant paper-like bracts surrounding small white flowers.",
          ecologicalBenefits: ["Attracts pollinators"],
          bloomingSeason: "summer",
        },
        {
          id: "creeping-fig",
          commonName: "Creeping Fig",
          scientificName: "Ficus pumila",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Creeping%20fig%20%28Ficus%20pumila%29.jpg-fjCiszGXKfSIqm6WUFAymEDWh1cpRm.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 15,
          droughtResistant: true,
          description: "Fast-growing climber with small heart-shaped leaves that cling to surfaces.",
          ecologicalBenefits: ["Wall coverage", "Insulation"],
          bloomingSeason: "rarely blooms",
        },
        {
          id: "wisteria",
          commonName: "Wisteria",
          scientificName: "Wisteria",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wisterias%20%28Wisteria%29.jpg-kQ8hh8x11RjwKJaoF2CIqaxRWX7KDU.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 900,
          droughtResistant: false,
          description: "Woody climbing vine known for its pendulous clusters of fragrant flowers.",
          ecologicalBenefits: ["Provides shade", "Attracts pollinators"],
          faunaDependency: ["Bees"],
          bloomingSeason: "spring",
        },
        {
          id: "bush-honeysuckle",
          commonName: "Bush Honeysuckle",
          scientificName: "Lonicera morrowii",
          type: "shrub",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/bush-honeysuckle.jpg",
          windResistance: "high",
          sunExposure: "partial",
          height: 250,
          droughtResistant: true,
          description: "Deciduous shrub with fragrant white flowers that turn yellow, followed by red berries.",
          ecologicalBenefits: ["Bird food", "Nectar source"],
          faunaDependency: ["Birds", "Butterflies"],
          bloomingSeason: "spring",
        },
        {
          id: "winter-aconite",
          commonName: "Winter Aconite",
          scientificName: "Eranthis hyemalis",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Winter%20Aconite%20%28Eranthis%20hyemalis%29.jpg-7fvSRFjkqBk4fNftFjgVm061k7F7vr.jpeg",
          windResistance: "low",
          sunExposure: "partial",
          height: 10,
          droughtResistant: false,
          description: "Early-blooming perennial with cup-shaped yellow flowers and collar-like bracts.",
          ecologicalBenefits: ["Early nectar source"],
          faunaDependency: ["Early pollinators"],
          bloomingSeason: "winter",
        },
        {
          id: "cypress-spurge",
          commonName: "Cypress Spurge",
          scientificName: "Euphorbia cyparissias",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cypress%20Spurge%20%28Euphorbia%20cyparissias%29.jpg-0XzClcbezYintxEYXIMtU8IS5m2nka.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 30,
          droughtResistant: true,
          description: "Herbaceous perennial with narrow blue-green leaves and yellow-green flowers.",
          ecologicalBenefits: ["Drought tolerance"],
          bloomingSeason: "spring",
        },
        {
          id: "creeping-jenny",
          commonName: "Creeping Jenny",
          scientificName: "Lysimachia nummularia",
          type: "groundcover",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Creeping%20Jenny%20%28Lysimachia%20nummularia%29.jpg-y0doqXU2lT4AW6IMWUmJEXDdUzL3Jz.jpeg",
          windResistance: "high",
          sunExposure: "partial",
          height: 5,
          droughtResistant: false,
          description: "Low-growing perennial with round leaves and bright yellow flowers.",
          ecologicalBenefits: ["Ground cover", "Erosion control"],
          bloomingSeason: "summer",
        },
        {
          id: "japanese-barberry",
          commonName: "Japanese Barberry",
          scientificName: "Berberis thunbergii",
          type: "shrub",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Japanese%20Barberry%20%28Berberis%20thunbergii%29.jpg-P5QtqVjcrLPLBfbnswjYFLCQVapjQt.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 150,
          droughtResistant: true,
          description: "Deciduous shrub with small oval leaves, thorny stems, and red berries.",
          ecologicalBenefits: ["Bird food"],
          faunaDependency: ["Birds"],
          bloomingSeason: "spring",
        },
        {
          id: "agapanthus",
          commonName: "African Lily",
          scientificName: "Agapanthus praecox",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/african-lily.jpg",
          windResistance: "medium",
          sunExposure: "full",
          height: 120,
          droughtResistant: true,
          description:
            "Clump-forming perennial with strap-like leaves and spherical clusters of blue or white flowers.",
          ecologicalBenefits: ["Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "sugar-bush",
          commonName: "Sugar Bush",
          scientificName: "Protea repens",
          type: "shrub",
          growthSpeed: "slow",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Sugar%20Bush%20%28Protea%20repens%29.jpg-CwJ7q6jUr2ELzVdZ4atnVMAcBxZVLw.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 300,
          droughtResistant: true,
          description: "Evergreen shrub with leathery leaves and distinctive cone-shaped flower heads.",
          ecologicalBenefits: ["Attracts birds", "Drought tolerance"],
          faunaDependency: ["Birds", "Insects"],
          bloomingSeason: "winter",
        },
        {
          id: "large-bullwort",
          commonName: "Large Bullwort",
          scientificName: "Ammi majus",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "annual",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Large%20bullwort%20%28Ammi%20majus%29-h5OCv2RKuGP5aYru9splvHeWi2J1GT.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 120,
          droughtResistant: false,
          description: "Annual herb with lacy white flower umbels similar to Queen Anne's lace.",
          ecologicalBenefits: ["Attracts beneficial insects"],
          faunaDependency: ["Butterflies", "Parasitic wasps"],
          bloomingSeason: "summer",
        },
        {
          id: "butterfly-bush",
          commonName: "Butterfly Bush",
          scientificName: "Rotheca myricoides",
          type: "shrub",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl: "/images/butterfly-bush.jpg",
          windResistance: "medium",
          sunExposure: "full",
          height: 200,
          droughtResistant: true,
          description: "Shrub with arching branches and cone-shaped clusters of fragrant flowers.",
          ecologicalBenefits: ["Attracts pollinators"],
          faunaDependency: ["Butterflies", "Bees", "Hummingbirds"],
          bloomingSeason: "summer",
        },
        {
          id: "water-mint",
          commonName: "Water Mint",
          scientificName: "Mentha aquatica",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Water%20mint%20%28Mentha%20aquatica%29.jpg-3MEMv75ONy0ddKbw4EtjbwzEi0bNDS.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 60,
          droughtResistant: false,
          description: "Aromatic perennial herb that grows in wet places with lilac flowers in dense whorls.",
          ecologicalBenefits: ["Attracts pollinators", "Water filtration"],
          faunaDependency: ["Bees", "Butterflies", "Aquatic insects"],
          bloomingSeason: "summer",
          maintenanceLevel: "moderate",
        },
        {
          id: "virginia-creeper",
          commonName: "Virginia Creeper",
          scientificName: "Parthenocissus quinquefolia",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Virginia%20creeper%20%28Parthenocissus%20quinquefolia%29.jpg-vYtLUZlA86XYvI2eVeknIGiu5HfByb.jpeg",
          windResistance: "high",
          sunExposure: "partial",
          height: 1500,
          droughtResistant: true,
          description: "Deciduous woody vine with five-leaved compound leaves that turn bright red in autumn.",
          ecologicalBenefits: ["Fall color", "Bird habitat"],
          faunaDependency: ["Birds"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "oregano",
          commonName: "Oregano",
          scientificName: "Origanum vulgare",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Oregano%20%28origanum%20vulgare%29.jpg-GDoTqJGlM5fslfhsI0mXgdvjhjuXi3.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 50,
          droughtResistant: true,
          description: "Aromatic herb with small purple or white flowers and culinary uses.",
          ecologicalBenefits: ["Attracts pollinators", "Culinary herb"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "climbing-hydrangea",
          commonName: "Climbing Hydrangea",
          scientificName: "Hydrangea anomala",
          type: "vine",
          growthSpeed: "slow",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Climbing%20hydrangea%20%28Hydrangea%20anomala%29.jpg-QdfMGxcOyMfXmQfzLFCTS2TR4rh9NP.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 1200,
          droughtResistant: false,
          description: "Woody vine with heart-shaped leaves and lacy white flower clusters.",
          ecologicalBenefits: ["Provides habitat", "Shade"],
          faunaDependency: ["Bees", "Birds"],
          bloomingSeason: "summer",
          maintenanceLevel: "moderate",
        },
        {
          id: "common-foxglove",
          commonName: "Common Foxglove",
          scientificName: "Digitalis purpurea",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "biennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20foxglove%20%28Digitalis%20purpurea%29.jpg-AzOIh0ndb8JEgAR5SkSPijcSVsCUa4.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 150,
          droughtResistant: false,
          description: "Tall biennial with spikes of tubular purple, pink or white flowers.",
          ecologicalBenefits: ["Attracts pollinators"],
          faunaDependency: ["Bees", "Bumblebees"],
          bloomingSeason: "summer",
          maintenanceLevel: "moderate",
        },
        {
          id: "broad-buckler-fern",
          commonName: "Broad Buckler Fern",
          scientificName: "Dryopteris dilatata",
          type: "fern",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/broad-buckler-fern.jpg",
          windResistance: "medium",
          sunExposure: "shade",
          height: 100,
          droughtResistant: false,
          description: "Elegant fern with triangular, three-times pinnate fronds forming a shuttlecock shape.",
          ecologicalBenefits: ["Woodland ground cover", "Habitat for small creatures"],
          bloomingSeason: "non-flowering",
        },
        {
          id: "male-fern",
          commonName: "Male Fern",
          scientificName: "Dryopteris filix-mass",
          type: "fern",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Male%20fern%20%28Dryopteris%20filix-mass%29.jpg-uHbisAj7gPdGJxFBcHEu8iq1eej0fW.jpeg",
          windResistance: "medium",
          sunExposure: "shade",
          height: 120,
          droughtResistant: false,
          description: "Robust fern with shuttlecock-like growth habit and lance-shaped fronds.",
          ecologicalBenefits: ["Soil stabilization", "Habitat for small creatures"],
          bloomingSeason: "non-flowering",
        },
        {
          id: "sweet-woodruff",
          commonName: "Sweet Woodruff",
          scientificName: "Galium odoratum",
          type: "groundcover",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Sweet%20woodruff%20%28Galium%20odoratum%29.jpg-2oS5sZ5GKSP59qYTkMJifuqrLnWrxt.jpeg",
          windResistance: "low",
          sunExposure: "shade",
          height: 30,
          droughtResistant: false,
          description: "Low-growing perennial with whorls of fragrant leaves and small white flowers.",
          ecologicalBenefits: ["Ground cover for shade", "Fragrance"],
          faunaDependency: ["Small pollinators"],
          bloomingSeason: "spring",
          maintenanceLevel: "low",
        },
        {
          id: "scotch-mist",
          commonName: "Scotch Mist",
          scientificName: "Galium sylvaticum",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Scotch%20mist%20%28Galium%20sylvaticum%29-Oxsmm1hLjPiljbe27L1gJUk3Ma6dCQ.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 80,
          droughtResistant: false,
          description: "Woodland herb with whorls of narrow leaves and tiny white star-shaped flowers.",
          ecologicalBenefits: ["Woodland ground cover"],
          faunaDependency: ["Small insects"],
          bloomingSeason: "summer",
        },
        {
          id: "dusky-cranes-bill",
          commonName: "Dusky Crane's-bill",
          scientificName: "Geranium phaeum",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dusky%20crane%27s-bill%20%28Geranium%20phaeum%29.jpg-qjZmXqzVu9pCW60FEuzwtlK8TVvd61.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 60,
          droughtResistant: false,
          description: "Woodland perennial with lobed leaves and distinctive dark purple-brown flowers.",
          ecologicalBenefits: ["Shade garden plant", "Attracts pollinators"],
          faunaDependency: ["Bees"],
          bloomingSeason: "spring",
        },
        {
          id: "water-avens",
          commonName: "Water Avens",
          scientificName: "Geum rivale",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Water%20avens%20%28Geum%20rivale%29.jpg-Hi9g9ejHE2SWxw0b5qOUdCcVBmkzcY.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 40,
          droughtResistant: false,
          description: "Moisture-loving perennial with nodding bell-shaped reddish-orange flowers.",
          ecologicalBenefits: ["Wetland plant", "Attracts pollinators"],
          faunaDependency: ["Bees", "Flies"],
          bloomingSeason: "spring",
          maintenanceLevel: "low",
        },
        {
          id: "yellow-flag",
          commonName: "Yellow Flag",
          scientificName: "Iris pseudacorus",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Yellow%20flag%20%28Iris%20pseudacorus%29.jpg-1IkHMSXSgTIFS0fsdlnffwUl9yFSny.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 150,
          droughtResistant: false,
          description: "Aquatic or marginal iris with bright yellow flowers and sword-like leaves.",
          ecologicalBenefits: ["Water filtration", "Wetland habitat"],
          faunaDependency: ["Dragonflies", "Aquatic insects"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "yellow-archangel",
          commonName: "Yellow Archangel",
          scientificName: "Lamiastrum galeobdolon",
          type: "groundcover",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lamiastrum%20galeobdolon%20%28Yellow%20archangel%29.jpg-JVShIZad5o7xpjFb6YiW2iFZlTz7ee.jpeg",
          windResistance: "medium",
          sunExposure: "shade",
          height: 30,
          droughtResistant: false,
          description: "Woodland groundcover with silver-variegated leaves and yellow hooded flowers.",
          ecologicalBenefits: ["Woodland ground cover", "Early nectar source"],
          faunaDependency: ["Bees"],
          bloomingSeason: "spring",
        },
        {
          id: "annual-honesty",
          commonName: "Annual Honesty",
          scientificName: "Lunaria annua",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "biennial",
          biodiversityValue: "medium",
          imageUrl: "/images/annual-honesty.jpg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 90,
          droughtResistant: false,
          description: "Biennial with purple flowers followed by distinctive silvery, translucent seed pods.",
          ecologicalBenefits: ["Attracts pollinators", "Self-seeds readily"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "spring",
        },
        {
          id: "perennial-honesty",
          commonName: "Perennial Honesty",
          scientificName: "Lunaria rediviva",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Perennial%20honesty%20%28Lunaria%20rediviva%29-hlRpfJut4wjy2UyxVV2PavwsRG6hqi.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 100,
          droughtResistant: false,
          description: "Woodland perennial with fragrant lilac flowers and elliptical seed pods.",
          ecologicalBenefits: ["Woodland plant", "Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "spring",
        },
        {
          id: "great-wood-rush",
          commonName: "Great Wood-rush",
          scientificName: "Luzula sylvatica",
          type: "grass",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Great%20wood-rush%20%28Luzula%20sylvatica%29-6A4TkkrkP3rFqbq4kjzLghk7ZorRk5.jpeg",
          windResistance: "high",
          sunExposure: "shade",
          height: 60,
          droughtResistant: false,
          description: "Evergreen woodland grass-like plant with broad, hairy leaves and airy flower clusters.",
          ecologicalBenefits: ["Woodland ground cover", "Erosion control"],
          bloomingSeason: "spring",
        },
        {
          id: "white-wood-rush",
          commonName: "White Wood-rush",
          scientificName: "Luzula luzuloides",
          type: "grass",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/White%20wood-rush%20%28Luzula%20luzuloides%29.jpg-A9e6F0VpWHFP1iv5yPnHhxAi3mDCwl.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 40,
          droughtResistant: false,
          description: "Woodland perennial with grass-like leaves and clusters of small white flowers.",
          ecologicalBenefits: ["Woodland ground cover"],
          bloomingSeason: "spring",
          maintenanceLevel: "low",
        },
        {
          id: "purple-loosestrife",
          commonName: "Purple Loosestrife",
          scientificName: "Lythrum salicaria",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Purple%20loosestrife%20%28Lythrum%20salicaria%29.jpg-ZFBC1g4Q1Y4T099wWzlK1TDVpDulyX.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 120,
          droughtResistant: false,
          description: "Tall wetland plant with spikes of magenta flowers.",
          ecologicalBenefits: ["Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "flat-pea",
          commonName: "Flat Pea",
          scientificName: "Lathyrus sylvestris",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Flat%20pea%20%28Lathyrus%20sylvestris%29-h6kUNr6Qa7PuHEVZupMfxp5dc9TgDZ.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 200,
          droughtResistant: true,
          description: "Climbing perennial with winged stems, paired leaflets, and pink-purple flowers.",
          ecologicalBenefits: ["Nitrogen fixation", "Wildlife food"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "european-honeysuckle",
          commonName: "European Honeysuckle",
          scientificName: "Lonicera periclymenum",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/European%20honeysuckle%20%28Lonicera%20periclymenum%29-eLCgSIOFrnde7mZIn4cdFm23F0N6gz.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 700,
          droughtResistant: false,
          description: "Twining deciduous climber with fragrant tubular flowers that change from white to yellow.",
          ecologicalBenefits: ["Night-scented flowers", "Berries for birds"],
          faunaDependency: ["Moths", "Birds", "Bees"],
          bloomingSeason: "summer",
        },
        {
          id: "common-mallow",
          commonName: "Common Mallow",
          scientificName: "Malva sylvestris",
          type: "flower",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20mallow%20%28Malva%20sylvestris%29.jpg-VAEhuf6j4Z9NCOUpo12ctonu8qPmDU.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 100,
          droughtResistant: true,
          description: "Upright perennial with lobed leaves and purple-veined pink flowers.",
          ecologicalBenefits: ["Attracts pollinators", "Edible and medicinal"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "anise",
          commonName: "Anise",
          scientificName: "Myrrhis odorata",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl: "/images/anise.jpg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 120,
          droughtResistant: false,
          description: "Aromatic perennial with fern-like leaves, white flowers, and anise-scented foliage.",
          ecologicalBenefits: ["Attracts beneficial insects", "Edible herb"],
          faunaDependency: ["Bees", "Hoverflies"],
          bloomingSeason: "spring",
        },
        {
          id: "royal-fern",
          commonName: "Royal Fern",
          scientificName: "Osmunda regalis",
          type: "fern",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Royal%20fern%20%28Osmunda%20regalis%29-PgpV7yYgU15H6BEjC5aFoYkHx3MDfx.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 150,
          droughtResistant: false,
          description: "Majestic fern with distinctive fertile fronds that turn rusty-brown when mature.",
          ecologicalBenefits: ["Wetland habitat", "Bank stabilization"],
          bloomingSeason: "non-flowering",
        },
        {
          id: "solomons-seal",
          commonName: "Solomon's Seal",
          scientificName: "Polygonatum multiflorum",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Solomon%27s%20seal%20%28Polygonatum%20multiflorum%29.jpg-LUcbW4XOwMbMndzBfZ095QHB2gvtCS.jpeg",
          windResistance: "low",
          sunExposure: "shade",
          height: 80,
          droughtResistant: false,
          description: "Woodland perennial with arching stems bearing dangling white bell-shaped flowers.",
          ecologicalBenefits: ["Woodland habitat", "Berries for birds"],
          faunaDependency: ["Bees", "Birds"],
          bloomingSeason: "spring",
        },
        {
          id: "ground-elder",
          commonName: "Ground Elder",
          scientificName: "Aegopodium podagraria",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ground%20elder%20%28Aegopodium%20podagraria%29.jpg-kJhFy4fa3gUEkjZgo0f2hJTzG6t2Ra.jpeg",
          windResistance: "high",
          sunExposure: "partial",
          height: 60,
          droughtResistant: true,
          description: "Vigorous groundcover with compound leaves and flat-topped clusters of white flowers.",
          ecologicalBenefits: ["Ground cover", "Early nectar source"],
          faunaDependency: ["Small insects", "Hoverflies"],
          bloomingSeason: "summer",
        },
        {
          id: "common-st-johns-wort",
          commonName: "Common St. John's Wort",
          scientificName: "Hypericum perforatum",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20St.%20John%27s%20wort%20%28Hypericum%20perforatum%29.jpg-gNOwJK53DILwUTJqRBIanyP7ti5o6f.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 80,
          droughtResistant: true,
          description: "Herbaceous perennial with yellow star-shaped flowers and distinctive translucent leaf glands.",
          ecologicalBenefits: ["Medicinal properties", "Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
          maintenanceLevel: "low",
        },
        {
          id: "greater-celandine",
          commonName: "Greater Celandine",
          scientificName: "Chelidonium majus",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Greater%20celandine%20%28Chelidonium%20majus%29-Tfa5LemN2O8GGD1JBN8UrkzBloUVeb.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 60,
          droughtResistant: false,
          description: "Herbaceous perennial with yellow flowers and orange sap with medicinal properties.",
          ecologicalBenefits: ["Early nectar source", "Medicinal plant"],
          faunaDependency: ["Bees", "Flies"],
          bloomingSeason: "spring",
        },
        {
          id: "sycamore",
          commonName: "Sycamore",
          scientificName: "Acer pseudoplatanus",
          type: "tree",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Sycamore%20%28Acer%20pseudoplatanus%29.jpg-jn4RQDzfarGWssUWea85WKE42uCXy2.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 3500,
          droughtResistant: true,
          description: "Large deciduous tree with distinctive flaking bark and maple-like leaves.",
          ecologicalBenefits: ["Carbon sequestration", "Habitat for wildlife"],
          faunaDependency: ["Birds", "Insects"],
          bloomingSeason: "spring",
          maintenanceLevel: "moderate",
        },
        {
          id: "common-selfheal",
          commonName: "Common Selfheal",
          scientificName: "Prunella vulgaris",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20selfheal%20%28Prunella%20vulgaris%29.jpg-E2cRDkz9uAQUbUqqNex4Wv8B2EpCJb.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 30,
          droughtResistant: true,
          description: "Low-growing perennial herb with violet-blue flowers in dense spikes.",
          ecologicalBenefits: ["Medicinal properties", "Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "elder",
          commonName: "Elder",
          scientificName: "Sambucus nigra",
          type: "shrub",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Elder%20%28Sambucus%20nigra%29.jpg-w2nn3QyYH5nIfGHQ2pgXlZlOkMqSl1.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 600,
          droughtResistant: false,
          description: "Deciduous shrub with flat-topped clusters of white flowers followed by black berries.",
          ecologicalBenefits: ["Food source for wildlife", "Medicinal properties"],
          faunaDependency: ["Birds", "Insects", "Small mammals"],
          bloomingSeason: "summer",
        },
        {
          id: "grey-willow",
          commonName: "Grey Willow",
          scientificName: "Salix cinerea",
          type: "tree",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Grey%20willow%20%28Salix%20cinerea%29.jpg-zQKtNf0Sg1cAukl0G25G4heOs23XkK.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 1000,
          droughtResistant: false,
          description: "Deciduous tree or large shrub with grey-green leaves and distinctive catkins.",
          ecologicalBenefits: ["Early pollen source", "Wetland stabilization"],
          faunaDependency: ["Early pollinators", "Birds"],
          bloomingSeason: "spring",
        },
        {
          id: "red-campion",
          commonName: "Red Campion",
          scientificName: "Silene dioica",
          type: "flower",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Red%20campion%20%28Silene%20dioica%29.jpg-VxgZEkSuyBeQTZzYvDAUml9ZNDzSWL.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 80,
          droughtResistant: false,
          description: "Woodland perennial with bright pink-red flowers and hairy stems.",
          ecologicalBenefits: ["Woodland ground cover", "Attracts pollinators"],
          faunaDependency: ["Bees", "Butterflies", "Moths"],
          bloomingSeason: "spring",
        },
        {
          id: "rosa-multiflora",
          commonName: "Rosa Multiflora",
          scientificName: "Rosa multiflora 'Grevillei'",
          type: "shrub",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Rosa%20multiflora%20%28Grevillei%29.jpg-yr1kl7o6NYGoUwpUAQj74GrVVo5m3Z.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 300,
          droughtResistant: true,
          description: "Vigorous climbing rose with clusters of small, fragrant white flowers.",
          ecologicalBenefits: ["Habitat for birds", "Rose hips for wildlife"],
          faunaDependency: ["Birds", "Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "solanum-dulcamaroides",
          commonName: "Solanum Dulcamaroides",
          scientificName: "Solanum dulcamaroides",
          type: "vine",
          growthSpeed: "fast",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Solanum%20dulcamaroides-jN38VwY9AZDrEfw585cLiUHjon08ez.jpeg",
          windResistance: "medium",
          sunExposure: "partial",
          height: 400,
          droughtResistant: true,
          description: "Climbing vine with purple star-shaped flowers and red berries.",
          ecologicalBenefits: ["Attracts pollinators", "Berries for birds"],
          faunaDependency: ["Birds", "Bees"],
          bloomingSeason: "summer",
        },
        {
          id: "common-dandelion",
          commonName: "Common Dandelion",
          scientificName: "Taraxacum officinale",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Common%20dandelion%20%28Taraxacum%20officinale%29-g0O6kGLR1Yizc3PMLv4C4oK5tvj2vo.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 30,
          droughtResistant: true,
          description: "Common perennial herb with yellow composite flowers and fluffy seed heads.",
          ecologicalBenefits: ["Early nectar source", "Edible and medicinal"],
          faunaDependency: ["Bees", "Butterflies", "Birds"],
          bloomingSeason: "spring",
        },
        {
          id: "red-clover",
          commonName: "Red Clover",
          scientificName: "Trifolium pratense",
          type: "herb",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Red%20clover%20%28Trifolium%20pratense%29.jpg-l6EiHLJTQGLKifdLLKgnnQkoJwGePu.jpeg",
          windResistance: "medium",
          sunExposure: "full",
          height: 50,
          droughtResistant: true,
          description: "Short-lived perennial with trifoliate leaves and reddish-purple flower heads.",
          ecologicalBenefits: ["Nitrogen fixation", "Soil improvement", "Nectar source"],
          faunaDependency: ["Bees", "Butterflies"],
          bloomingSeason: "summer",
        },
        {
          id: "stinging-nettle",
          commonName: "Stinging Nettle",
          scientificName: "Urtica dioica",
          type: "herb",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Stinging%20nettle%20%28Urtica%20dioica%29.jpg-JhiNR3REanLEOP5OmMyGnwJJOnq3Bf.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 150,
          droughtResistant: false,
          description: "Herbaceous perennial with serrated leaves covered in stinging hairs.",
          ecologicalBenefits: ["Host plant for butterflies", "Edible and medicinal"],
          faunaDependency: ["Butterfly larvae", "Moths"],
          bloomingSeason: "summer",
        },
        {
          id: "sweet-violet",
          commonName: "Sweet Violet",
          scientificName: "Viola odorata",
          type: "flower",
          growthSpeed: "slow",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Sweet%20violet%20%28Viola%20odorata%29.jpg-FJF9RKaC3ACMx0Kkm4dHad8mwNDeIx.jpeg",
          windResistance: "low",
          sunExposure: "shade",
          height: 15,
          droughtResistant: false,
          description: "Low-growing perennial with heart-shaped leaves and fragrant purple flowers.",
          ecologicalBenefits: ["Early nectar source", "Fragrance"],
          faunaDependency: ["Early pollinators"],
          bloomingSeason: "spring",
          maintenanceLevel: "low",
        },
        {
          id: "english-oak",
          commonName: "English Oak",
          scientificName: "Quercus robur",
          type: "tree",
          growthSpeed: "slow",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "very high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/English%20oak%20%28Quercus%20robur%29.jpg-HU54fS2aGUGGxtMed8uAKXWvqnMRn2.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 3000,
          droughtResistant: true,
          description: "Majestic deciduous tree with lobed leaves and distinctive acorns.",
          ecologicalBenefits: ["Supports hundreds of species", "Carbon sequestration", "Habitat"],
          faunaDependency: ["Birds", "Insects", "Mammals", "Fungi"],
          bloomingSeason: "spring",
        },
        {
          id: "wych-elm",
          commonName: "Wych Elm",
          scientificName: "Ulmus glabra",
          type: "tree",
          growthSpeed: "medium",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "high",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wych%20elm%20%28Ulmus%20glabra%29.jpg-KXjdeDU60xTrTVLZSl9lUGD1qNiZ3O.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 4000,
          droughtResistant: false,
          description: "Large deciduous tree with asymmetrical leaves and distinctive winged seeds.",
          ecologicalBenefits: ["Habitat for wildlife", "Supports insects"],
          faunaDependency: ["Birds", "Insects"],
          bloomingSeason: "spring",
          maintenanceLevel: "high",
        },
        {
          id: "yorkshire-fog",
          commonName: "Yorkshire Fog",
          scientificName: "Holcus lanatus",
          type: "grass",
          growthSpeed: "fast",
          nativeStatus: "native",
          lifespan: "perennial",
          biodiversityValue: "medium",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Yorkshire%20Fog%20%28Holcus%20lanatus%29-VZFiLvUDfmezc4XBjWl8riPROsPaxR.jpeg",
          windResistance: "high",
          sunExposure: "full",
          height: 80,
          droughtResistant: true,
          description: "Soft, hairy perennial grass with pinkish-purple inflorescences.",
          ecologicalBenefits: ["Soil stabilization", "Wildlife habitat"],
          faunaDependency: ["Small mammals", "Birds"],
          bloomingSeason: "summer",
        },
        {
          id: "swiss-cheese-plant",
          commonName: "Swiss Cheese Plant",
          scientificName: "Monstera deliciosa",
          type: "vine",
          growthSpeed: "medium",
          nativeStatus: "non-native",
          lifespan: "perennial",
          biodiversityValue: "low",
          imageUrl:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Swiss%20Cheese%20Plant%20%28Monstera%20deliciosa%29-ZjUUgkOCjy0Toh4m6Mt7ryLRTsNkSo.png",
          windResistance: "low",
          sunExposure: "partial",
          height: 300,
          droughtResistant: false,
          description: "Climbing evergreen with large, glossy, perforated leaves.",
          ecologicalBenefits: ["Air purification", "Tropical aesthetic"],
          bloomingSeason: "rarely blooms",
        },
      ])
    }, 1000)
  })
}

export async function fetchPlantById(id: string): Promise<Plant | null> {
  const plants = await fetchPlants()
  const plant = plants.find((plant) => plant.id === id)
  return plant || null
}
