export const monthlyClimateData = [
  {
    month: "Jan",
    temperature: 2.5,
    rainfall: 75,
    sunlight: 2,
    windSpeed: 6.5,
  },
  {
    month: "Feb",
    temperature: 3,
    rainfall: 60,
    sunlight: 3,
    windSpeed: 6,
  },
  {
    month: "Mar",
    temperature: 6,
    rainfall: 50,
    sunlight: 4,
    windSpeed: 5.5,
  },
  {
    month: "Apr",
    temperature: 10,
    rainfall: 40,
    sunlight: 6,
    windSpeed: 5,
  },
  {
    month: "May",
    temperature: 14,
    rainfall: 55,
    sunlight: 7,
    windSpeed: 4.5,
  },
  {
    month: "Jun",
    temperature: 17,
    rainfall: 70,
    sunlight: 7.5,
    windSpeed: 4,
  },
  {
    month: "Jul",
    temperature: 19,
    rainfall: 80,
    sunlight: 7,
    windSpeed: 4,
  },
  {
    month: "Aug",
    temperature: 18.5,
    rainfall: 85,
    sunlight: 6.5,
    windSpeed: 4.5,
  },
  {
    month: "Sep",
    temperature: 15,
    rainfall: 75,
    sunlight: 5,
    windSpeed: 5,
  },
  {
    month: "Oct",
    temperature: 11,
    rainfall: 80,
    sunlight: 3.5,
    windSpeed: 5.5,
  },
  {
    month: "Nov",
    temperature: 6.5,
    rainfall: 90,
    sunlight: 2.5,
    windSpeed: 6,
  },
  {
    month: "Dec",
    temperature: 3.5,
    rainfall: 85,
    sunlight: 2,
    windSpeed: 6.5,
  },
]

export const rotterdamClimateZones = [
  {
    id: "north",
    name: "Rotterdam North",
    temperature: { min: 8, max: 19 },
    windExposure: 3,
    sunExposure: 4,
    description: "Urban area with slightly higher temperatures due to urban heat island effect.",
  },
  {
    id: "south",
    name: "Rotterdam South",
    temperature: { min: 7, max: 18 },
    windExposure: 3,
    sunExposure: 3,
    description: "Mixed urban and green areas with moderate temperatures.",
  },
  {
    id: "east",
    name: "Rotterdam East",
    temperature: { min: 6, max: 17 },
    windExposure: 2,
    sunExposure: 3,
    description: "Transition zone between urban and rural areas.",
  },
  {
    id: "west",
    name: "Rotterdam West",
    temperature: { min: 9, max: 20 },
    windExposure: 4,
    sunExposure: 4,
    description: "Coastal influence with higher winds and slightly milder winters.",
  },
]
